// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202175513_SeedVillas")]
    partial class SeedVillas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 12, 2, 18, 55, 12, 718, DateTimeKind.Local).AddTicks(3497),
                            Details = "Details",
                            ImageUrl = "https://www.lecollectionist.com/en/luxury-rental/villa-cavillonne-grimaud",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 12, 2, 18, 55, 12, 719, DateTimeKind.Local).AddTicks(8473),
                            Details = "Details",
                            ImageUrl = "https://media.inmobalia.com/imgV1/B98Le8~d7M9k3DegigWkzHXQlgzMFGqGJJp6ZRUcpX033lqadFBp2i4GGW4X2J1jIJ9Pwc6GsJX5cPSaC8Y5L~JfyHdu4Kip1k1F_9jq2QL1VlZkhoZwz17cTlFZNkNz3cS1P_oNeDi2nalfIzOHCukLbLsWTdvHO7XeSjMdZ_Z0_Ly766bTtu6PR960e0cp3S3nu~K~6B6gKJ0EHmX9y3T8_7P4AKNIUzg5bomJ14gPD0j7n2GO4RUmUotYoxhsgFwD~xK1l6gyQ~jJev0BEsdf7j29W1qY55FPh6RRQVme_TpPQ6P3p3jlwdsdQIbggg--.jpg",
                            Name = "Queen Villa",
                            Occupancy = 2,
                            Rate = 400.0,
                            Sqft = 850,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 12, 2, 18, 55, 12, 719, DateTimeKind.Local).AddTicks(8487),
                            Details = "Details",
                            ImageUrl = "https://media.inmobalia.com/imgV1/B95mbh8olwFQm~uCUaVOI2kQT0hb0a8sZ9turUNfnwtvuccYCzs0YVPfPbfkc2VnnN1JFDpiXNU9xzJ~Ag4BlYYPYZFIAjR7mCUc5JBLZPdgYJCxR1v5rEuUzU_c2l5t5RfA9A4ibbDcCe10wLVTA1gzagr2V3lBJiT7AZrQwB0hDkvTgaLD_paCEArhEnq8vZRo~5EsD4KnhBpeRR6wl14AfUVUY9d3J9Ih5kJFwzq7eRBg1Xs1c8fBJ3sutGCYoLfMyae~hKabvRxbS02z508fgWrSsd~RZvDcxlVTBWcMS~92Gj21s9Oizf2_G83WhPaqKRghQiWKpV3e6JPRkBrUnDS9vb91IqeGGkR5fc_~y5iYifxFGDsBRMuXKTp7HcnjfKB19Nuw50aPfi7uBdn_fyl5sd0qS17J1WQgSCpiyK_6K_Ozqg--.jpg",
                            Name = "The Breeze Villa",
                            Occupancy = 8,
                            Rate = 100.0,
                            Sqft = 250,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
